### ISSUE TITLE
thread safety bug

### ISSUE THREAD

**Issue by NoAvailableAlias** [dacap/observable#1]
Hello,

I have added your implementation of signals to [this benchmark project here](https://github.com/NoAvailableAlias/signal-slot-benchmarks/blob/master/results_msvc/README.md). However, it appears that there is either a bug in dacap/observable in regards to thread safety or [my integration](https://github.com/NoAvailableAlias/signal-slot-benchmarks/blob/master/benchmark/hpp/benchmark_dob.hpp) is missing something.

I'm currently working on adding more implementations of signals and slots to this benchmark project so I don't currently have the time to investigate the issue further. If you find anything / resolve anything update this bug and I'll get those changes integrated.

(on a side note I had to modify some file names/includes in order for dacap/observable to play nice in an environment full of signal slot implementations)

Matt M.

**Comment by dacap** [comment]
Hi Matt, actually I'm not aware about some thread safety issues but I'm pretty sure they might exist.

There are some tests using [-fsanitize=thread](https://github.com/dacap/observable/blob/06ee7f9c6fd03f4d5d542f7a23773d6acdc9dc47/.travis.yml#L12) and I've fixed some problems before about this, but maybe I could add new tests with to check threads issues.

Can you pointing me out about the code that is creating thread, connecting, and calling signals in your project?

**Comment by NoAvailableAlias** [comment]
Sure thing, [here is the specific method](https://github.com/NoAvailableAlias/signal-slot-benchmarks/blob/master/benchmark.hpp#L185) that I run all thread safe signal libraries against.

The benchmarks were designed to abstract the benchmark test method away from all other signal libraries using templates. "Foo" in this case refers to your specific benchmark class "Dob" in benchmark/hpp/benchmark_dob.hpp

**Comment by dacap** [comment]
@NoAvailableAlias check the latest commit, the crash should be fixed now. Thank you very much for reporting this and your work on `signal-slot-benchmarks`! Tell me if the problem continues.

In a future I'd love to improve the performance of this library too.

**Comment by dacap** [comment]
(I'm checking automated tests in CI and someone are failing. So there is another bug in the code.)

**Comment by dacap** [comment]
@NoAvailableAlias finally the commit 873cd8d7fd04bb024ab42350f2c4aca4d4b35bec should fix this issue.

**Comment by NoAvailableAlias** [comment]
Just finished pulling your changes and have updated [your results here](https://github.com/NoAvailableAlias/signal-slot-benchmarks/tree/master/results_msvc). Looks like everything is good to go. Nice work resolving this issue so fast btw!
